const actionTypes = {
  CHANGE_PHONE: "CHANGE_PHONE",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  LOGIN_START: "LOGIN_START",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  GET_USERS: "GET_USERS",
  ERROR_GETTING_USERS: "ERROR_GETTING_USERS",
  GET_PROFILE_DATA: "GET_PROFILE_DATA",
  ERROR_GETTING_PROFILE_DATA: "ERROR_GETTING_PROFILE_DATA",
};

export default actionTypes;
